// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHdLaSxe5fzcKDATauomwauD5r8pnoVTU',
    appId: '1:1065724490432:web:6bbff49a55a05ac23ef325',
    messagingSenderId: '1065724490432',
    projectId: 'transit-app-19ec3',
    authDomain: 'transit-app-19ec3.firebaseapp.com',
    databaseURL: 'https://transit-app-19ec3-default-rtdb.firebaseio.com',
    storageBucket: 'transit-app-19ec3.firebasestorage.app',
    measurementId: 'G-9E4XPHX240',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAafY-oDR4QTVjBXF_xUh0LTrfmSl1TVcE',
    appId: '1:202313590028:android:b88b6c3257711fe7c4d529',
    messagingSenderId: '202313590028',
    projectId: 'transit-data-7adc4', // Critical update
    databaseURL: 'https://transit-data-7adc4-default-rtdb.firebaseio.com',
    storageBucket: 'transit-data-7adc4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGlvZo0a21k0NZ4lRrFCaa3N8cFk31f_s',
    appId: '1:1065724490432:ios:8b5024f52c85ac3e3ef325',
    messagingSenderId: '1065724490432',
    projectId: 'transit-app-19ec3',
    databaseURL: 'https://transit-app-19ec3-default-rtdb.firebaseio.com',
    storageBucket: 'transit-app-19ec3.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGlvZo0a21k0NZ4lRrFCaa3N8cFk31f_s',
    appId: '1:1065724490432:ios:8b5024f52c85ac3e3ef325',
    messagingSenderId: '1065724490432',
    projectId: 'transit-app-19ec3',
    databaseURL: 'https://transit-app-19ec3-default-rtdb.firebaseio.com',
    storageBucket: 'transit-app-19ec3.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHdLaSxe5fzcKDATauomwauD5r8pnoVTU',
    appId: '1:1065724490432:web:372c0fb67f49c44d3ef325',
    messagingSenderId: '1065724490432',
    projectId: 'transit-app-19ec3',
    authDomain: 'transit-app-19ec3.firebaseapp.com',
    databaseURL: 'https://transit-app-19ec3-default-rtdb.firebaseio.com',
    storageBucket: 'transit-app-19ec3.firebasestorage.app',
    measurementId: 'G-DNLETHZ4GQ',
  );
}
